libgpsd_core.c:520: warning: no previous prototype for `gpsd_error_model' gpsd.c:1678: warning: implicit declaration of function `gpsd_error_model'
gpsd_error_model_fixup got renamed, but the prototype was overlooked. oops.